### ISSUE TITLE
NOTICE: NVIDIA Cloud Native Core fails due to CUDA linux repository GPG key rotation

### ISSUE THREAD

**Issue by erikbohnhorst** [NVIDIA/cloud-native-stack#22]
**Issue**

Pre-existing Cloud Native Core installation stopped working after a reboot. 
`Note:` Installations deployed on 04/29 or later are not impacted.

**What happened:**

NVIDIA team rotated GPG keys for CUDA linux repositories on 4/28. More information on this can be found [here](https://forums.developer.nvidia.com/t/notice-cuda-linux-repository-key-rotation/212772). CUDA repository is included in the NVIDIA driver images deployed through GPU operator and causing failures during apt-get update on Ubuntu 20.04. This happens whenever current running driver containers are restarted or node reboots. 

Following error message will be seen from driver Pod (nvidia-driver-ctr container):

```
Updating` the package cache...
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is no longer signed.
```

**Fix:**
#### Option 1 - Uninstall and re-install
1. bash setup.sh uninstall
2. bash setup.sh install

#### Option 2 - Repair
- Repair existing Cloud Native Core installation by updating the clusterpolicy.
- Go to the [GPU Operator Issue #344](https://github.com/NVIDIA/gpu-operator/issues/344) to see the exact steps.

**Comment by evberrypi** [comment]
Fix (Debian, Ubuntu, WSL):
1. Set $distro and $arch variables listed [here](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/)
2. Run:
```bash
sudo apt-key del 7fa2af80

sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/$distro/$arch/3bf863cc.pub
```

[Source](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/)
