### ISSUE TITLE
CNC deployment fails with error message: Unsupported parameters for (apt) module: allow_change_held_packages

### ISSUE THREAD

**Issue by francisguillier** [NVIDIA/cloud-native-stack#28]
TASK [Install kubernetes components for Ubuntu on NVIDIA Cloud Native Core 7.1] ***********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (apt) module: allow_change_held_packages. Supported parameters include: dpkg_options, state, install_recommends (install-recommends), update_cache (update-cache), autoclean, lock_timeout, force_apt_get, deb, allow_unauthenticated (allow-unauthenticated), purge, update_cache_retry_max_delay, package (name, pkg), autoremove, only_upgrade, force, update_cache_retries, allow_downgrade (allow-downgrade, allow-downgrades, allow_downgrades), cache_valid_time, fail_on_autoremove, policy_rc_d, upgrade, default_release (default-release)."}

**Comment by francisguillier** [comment]
root cause:
ansible version must be >= 2.13.3

to fix the issue:
$ sudo apt remove ansible
$ sudo apt install pip

that's all.
perform a new deployment (bash setup.sh install) and it should go through

**Comment by angudadevops** [comment]
@francisguillier this issue fixed and tested, please clone it and test it again.

**Comment by angudadevops** [comment]
Closing this issue as it's already fixed.

Thanks
Anurag
