### ISSUE TITLE
Ansible playbook should install latest CNC

### ISSUE THREAD

**Issue by evberrypi** [NVIDIA/cloud-native-stack#31]
Possible slight oversight. 
Cloning the repo and running installed v6.3 of CNC, not latest 8.0.

Was this intentional?

**Comment by evberrypi** [comment]
PR up:  #32

**Comment by angudadevops** [comment]
@evberrypi  6.3 version targeted for NVIDIA Certification process but feel free to change the version as required. we will change the version to 8.1 soon, please stay tuned.
