### ISSUE TITLE
Ansible 7.0.0 removes "warn" parameter for ansible.legacy.command

### ISSUE THREAD

**Issue by tmckayus** [NVIDIA/cloud-native-stack#35]
"setup.sh install" pip install the latest ansible package, which is currently 7.0.0 (recently released). Apparently support for the "warn" parameter to ansible.legacy.command has been removed.

Suggestion is to remove the "warn" parameters in all *.yaml files, and perhaps pin the ansible version to a specific version in setup.sh to avoid unexpected changes in the future.

As a quick fix for a local checkout, the current CNS will work if ansible 6.0.0 is installed, for example in setup.sh replace the ansible install with the following line:

pip3 install ansible==6.0.0 2>&1 >/dev/null

**Comment by angudadevops** [comment]
@tmckayus updated the code where we stick to Ansible 7.0.0 version with supported parameters, please let us know once you test with latest code.

**Comment by tmckayus** [comment]
@angudadevops thank you! I tested this with cuOpt and it is working well

**Comment by tmckayus** [comment]
https://github.com/NVIDIA/cuOpt-Resources/pull/27
