### ISSUE TITLE
cnc_values.yaml references old version of CNS

### ISSUE THREAD

**Issue by evberrypi** [NVIDIA/cloud-native-stack#39]
In [CNC_Values.yaml](https://github.com/NVIDIA/cloud-native-stack/blob/c8d7ca78a8a7f87cde76b92ea1c364b0514b9ec2/playbooks/cnc_values.yaml#L1), it has `cnc_version: 6.3` however there is another input with this value inside of `cnc_version.yaml` which sets `cnc_version: 8.1`. 

This might be confusing to users.

Is is possible to just have one value setting `cnc_version` and have it default to the latest (eg `9.0`)?

**Comment by aguda-nvidia** [comment]
@evberrypi 8.1 is focused for NVIDIA Certified Systems, that's where default version set to 8.1

But user always has an option to change this value.
