### ISSUE TITLE
Lost internet connection after run cnc-uninstall

### ISSUE THREAD

**Issue by helenzhou0523** [NVIDIA/cloud-native-stack#51]
Hi, 

I was using the cnc-uninstall. But after `iptables -F` command, my machine lost internet connection. I need to restart the machine. The following installation cannot be done due to this step. Could someone explain what might cause this and how to resolve please?

Thanks,

**Comment by angudadevops** [comment]
@helenzhou0523 as part of uninstall we need to clean IP tables to remove any existing kubernetes ports info but if your system is configured with static network configuration whenever you trigger uninstall that might flush the network config to loose the connectivity.

**Comment by angudadevops** [comment]
@helenzhou0523 let us know if you need any further information. thanks
