### ISSUE TITLE
Remote Ansible Installs Fail

### ISSUE THREAD

**Issue by BHSDuncan** [NVIDIA/cloud-native-stack#57]
The `k8s-install.yaml` file used in `playbooks/` makes use of `ansible_user_dir`, but when doing a remote install, unless the username used for the remote is the same on the localhost (i.e. is already a user on the local system from which the playbook is kicked off), the playbook will fail with a permissions issue around line 276.

I verified this by creating a user on a local machine that kicks off the playbook (in fact, just a user dir in `/home/` with the appropriate name and setting r/w permissions temporarily). Uninstalling and then re-running the playbook then works.

It looks like the change was done last year sometime: https://github.com/NVIDIA/cloud-native-stack/commit/55bdd53be90398b23dff1da95681d6afc88bab44

**Comment by angudadevops** [comment]
@BHSDuncan I have changed to `/tmp` and tested with different user on remote machines. works for me, please pull the latest and let us know if you still hit any issues. 

Thanks

**Comment by angudadevops** [comment]
@BHSDuncan closing this issue as it's fixed
