### ISSUE TITLE
MicroK8s alias wasn't working end to end

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/cloud-native-stack#61]
I ran through a 11.1 install with microk8s enabled.

Directly running the validate script after running the setup script failed.

Rather than doing an `alias` in the Ansible and putting this information into .bashrc it would be more consistent to add the ansible-equivalent of the below lines because the bashrc alias do not seem to get picked up by the Ansible user.

```
sudo snap alias microk8s.kubectl kubectl
sudo snap alias microk8s.helm helm
```

**Comment by angudadevops** [comment]
@supertetelman Validation script is not support for microk8s yet, we're still working on it
we've tried to add that snap alias on Ansible and it didn't work before but I will double check and let you know 

Thanks
