### ISSUE TITLE
Hosts file example is inaccurate

### ISSUE THREAD

**Issue by ericrife** [NVIDIA/cloud-native-stack#68]
The current example of the hosts file is

[master]
<master-IP> ansible_ssh_user=nvidia ansible_ssh_pass=nvidipass ansible_sudo_pass=nvidiapass ansible_ssh_common_args='-o StrictHostKeyChecking=no'
[node]
<worker-IP> ansible_ssh_user=nvidia ansible_ssh_pass=nvidiapass ansible_sudo_pass=nvidiapass ansible_ssh_common_args='-o StrictHostKeyChecking=no'

The secondary node designation is not accurate. The ansible scripts are looking for an entry of "nodes". Please update the example on the page to accurately reflect what needs to be set.

**Comment by angudadevops** [comment]
@ericrife Readme Updated
