### ISSUE TITLE
chroot: failed to run command ‘nvidia-smi’: No such file or directory

### ISSUE THREAD

**Issue by rc0403126** [NVIDIA/cloud-native-stack#75]
Hello,

I'm currently running NV-Cert on x86_64 platform, with Hoppers.
NV-Cert uses cloud-native-stack.

However, when I'm running the script of `./runall.mig.sh`, the script prints below error messages,
`chroot: failed to run command ‘nvidia-smi’: No such file or directory`
Then I install the driver manually, which makes me allow to run `nvidia-smi` on host.

But still get the same error message.
**Can I know where would be the root of the `chroot`? Where should I link my command to?**

Many thanks!

---

Reproduce:
1. Install Ubuntu 22.04
2. `sudo apt-get install -y build-essential`
3. `sudo apt update` && `sudo apt upgrade`
4. `sudo init 6`
5. Disable Nouveau

(below runs with account `nvidia` under `/nvidia/`)

6. Clone cloud-native-stack package
7. Run with cns 12.1 and modify cns_version_12.1.yaml as below
> `enable_gds: yes `
> `enable_rdma: yes `
> `use_open_kernel_module: yes`

8. Install with `bash setup.sh install`
9. Run NV-Cert with `./runall.mig.sh` under `NCS/`

**Comment by angudadevops** [comment]
@rc0403126 please raise a NVBug if this is part of NVCert program

**Comment by rc0403126** [comment]
@angudadevops got you, thx!
